version: '2'
services:

  grafana:
    image: grafana/grafana
    volumes:
      - data:/var/lib/grafana
      - ./dashboards:/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini
      # Uncomment these to override the logo and favicon in Grafana
      #- ./img/powerdns-logo.svg:/usr/share/grafana/public/img/grafana_icon.svg:ro
      #- ./img/powerdns-favicon.png:/usr/share/grafana/public/img/fav32.png:ro
    ports:
      - "13000:3000"
    environment:
      GF_USERS_DEFAULT_THEME: light
      #GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - net

  graphiteapi:
    build: graphite-api/
    ports:
      - "18003:8000"
    volumes:
      - graphiteapi:/src/graphite
      - ./graphite-api/metronome:/usr/local/lib/python2.7/dist-packages/metronome
      # To allow updates without rebuilds
      - ./graphite-api/graphite-api.yaml:/etc/graphite-api.yaml
    networks:
      - net
    # We need a lot of worker processes. Graphite-API does not appear to be threadsafe...
    command: gunicorn -b 0.0.0.0:8000 -w 8 --timeout 30 --reload --log-level debug --access-logfile - --access-logformat '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s [%(L)ss] %(p)s' graphite_api.app:app
  
  # Gunicorn with sync worker processes does not work well with grafana, so we run it behind nginx
  graphiteproxy:
    image: nginx:stable-alpine
    volumes:
     - ./graphite-api/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - "18002:80"
    networks:
      - net

volumes:
  data:
    driver: local
  graphiteapi:
    driver: local

networks:
  net:
